# Copyright (c) 2026, Zvomaita Technologies (Pvt) Ltd and contributors
# For license information, please see license.txt

"""Bulk-update Forwarding Job service milestones from a clearing agent's
daily Excel tracking report. Used by the `Milestone Import Run` doctype,
which drives the preview/apply flow one service module at a time.

Column matching is two-layered: every active Milestone Definition in the
chosen module is matched by its own label (so the tool works immediately,
with no configuration), then any explicit row in
FreightMas Settings > Milestone Import Column Map for that module overrides
the header text (for when the agent's wording differs from the system
label). The same resolution feeds the downloadable Excel template, so a
template generated by this tool always re-imports cleanly.
"""

from io import BytesIO
from datetime import date, datetime

import openpyxl
import frappe
from frappe import _
from frappe.utils import getdate, nowdate
from frappe.utils.xlsxutils import build_xlsx_response

from freightmas.utils.permissions import check_freightmas_role

MILESTONE_TABLE_FIELDS = {
	"Road Freight": "road_freight_milestones",
	"Port Clearance": "port_clearance_milestones",
	"Border Clearance": "border_clearance_milestones",
	"Warehouse": "warehouse_milestones",
}


def _resolve_column_map(service_module):
	"""Build {header_lower: {milestone, milestone_code, milestone_label,
	service_module}} for one service module: start from every active
	Milestone Definition's own label, then overlay explicit
	FreightMas Settings > Milestone Import Column Map rows for the same
	module (explicit wording wins). A label collision (two active
	definitions normalising to the same header) is dropped rather than
	guessed - callers will then report it as an unmapped column.

	Also returns header_by_code: {milestone_code: canonical header text},
	using the same explicit-over-fallback precedence, so the downloadable
	template always uses exactly the header text that will match on import."""
	definitions = frappe.get_all(
		"Milestone Definition",
		filters={"service_module": service_module, "is_active": 1},
		fields=["name", "milestone_code", "milestone_label"],
		order_by="sequence asc",
	)
	if not definitions:
		frappe.throw(_("No active milestones are defined for {0}.").format(service_module))

	column_map = {}
	header_by_code = {}
	ambiguous = set()
	for definition in definitions:
		key = definition.milestone_label.strip().lower()
		entry = {
			"milestone": definition.name,
			"milestone_code": definition.milestone_code,
			"milestone_label": definition.milestone_label,
			"service_module": service_module,
		}
		if key in column_map and column_map[key]["milestone_code"] != definition.milestone_code:
			ambiguous.add(key)
		column_map[key] = entry
		header_by_code[definition.milestone_code] = definition.milestone_label
	for key in ambiguous:
		column_map.pop(key, None)

	settings = frappe.get_single("FreightMas Settings")
	job_reference_header = (settings.job_reference_column_header or "Job Reference").strip().lower()

	definitions_by_name = {d.name: d for d in definitions}
	for row in settings.milestone_import_column_map or []:
		if not row.column_header or not row.milestone:
			continue
		definition = definitions_by_name.get(row.milestone)
		if not definition:
			continue  # not active / not in this module
		column_map[row.column_header.strip().lower()] = {
			"milestone": definition.name,
			"milestone_code": definition.milestone_code,
			"milestone_label": definition.milestone_label,
			"service_module": service_module,
		}
		header_by_code[definition.milestone_code] = row.column_header

	return job_reference_header, column_map, header_by_code


def _read_workbook(file_url):
	file_doc = frappe.get_doc("File", {"file_url": file_url})
	workbook = openpyxl.load_workbook(BytesIO(file_doc.get_content()), data_only=True)
	sheet = workbook.worksheets[0]
	rows = list(sheet.iter_rows(values_only=True))
	if not rows:
		frappe.throw(_("The uploaded file is empty."))

	headers = [str(cell).strip() if cell is not None else "" for cell in rows[0]]
	return headers, rows[1:]


def _parse_cell_date(value):
	if value in (None, ""):
		return None
	if isinstance(value, (datetime, date)):
		return getdate(value)
	try:
		return getdate(str(value).strip())
	except Exception:
		return None


def classify_rows(headers, data_rows, job_reference_header, column_map):
	"""Pure classification - matches every (job, milestone) cell against the
	resolved column map and returns the 5-bucket preview payload. Writes
	nothing. Callers are responsible for role/permission gating."""
	header_lookup = {header.strip().lower(): idx for idx, header in enumerate(headers) if header}
	job_ref_idx = header_lookup.get(job_reference_header)
	if job_ref_idx is None:
		frappe.throw(
			_("Could not find the Job Reference column '{0}' in the uploaded file.").format(
				job_reference_header
			)
		)

	milestone_columns = []
	unmapped_columns = []
	for idx, header in enumerate(headers):
		if idx == job_ref_idx or not header:
			continue
		mapping = column_map.get(header.strip().lower())
		if mapping:
			milestone_columns.append((idx, mapping))
		else:
			unmapped_columns.append(header)

	if not milestone_columns:
		frappe.throw(
			_("None of the columns in the uploaded file match an active milestone for this module.")
		)

	to_update = []
	already_done = []
	unmatched_jobs = []
	milestone_not_enabled = []
	job_cache = {}

	for row in data_rows:
		if job_ref_idx >= len(row) or not row[job_ref_idx]:
			continue
		job_ref = str(row[job_ref_idx]).strip()
		if not job_ref:
			continue

		if job_ref not in job_cache:
			if frappe.db.exists("Forwarding Job", job_ref):
				job_cache[job_ref] = frappe.get_doc("Forwarding Job", job_ref)
			else:
				job_cache[job_ref] = None
				unmatched_jobs.append(job_ref)

		job = job_cache[job_ref]
		if not job:
			continue

		for idx, mapping in milestone_columns:
			if idx >= len(row):
				continue
			completed_on = _parse_cell_date(row[idx])
			if not completed_on:
				continue

			fieldname = MILESTONE_TABLE_FIELDS.get(mapping["service_module"])
			milestone_rows = job.get(fieldname) or [] if fieldname else []
			target_row = next(
				(r for r in milestone_rows if r.milestone_code == mapping["milestone_code"]), None
			)
			if not target_row:
				milestone_not_enabled.append(
					{
						"job": job_ref,
						"milestone_label": mapping["milestone_label"],
						"service_module": mapping["service_module"],
					}
				)
				continue

			entry = {
				"job": job_ref,
				"fieldname": fieldname,
				"row_name": target_row.name,
				"milestone_code": mapping["milestone_code"],
				"milestone_label": target_row.milestone_label,
				"completed_on": str(completed_on),
			}
			if target_row.is_completed:
				entry["existing_completed_on"] = (
					str(target_row.completed_on) if target_row.completed_on else None
				)
				already_done.append(entry)
			else:
				to_update.append(entry)

	return {
		"to_update": to_update,
		"already_done": already_done,
		"unmatched_jobs": unmatched_jobs,
		"milestone_not_enabled": milestone_not_enabled,
		"unmapped_columns": unmapped_columns,
	}


def apply_updates(updates):
	"""Write exactly the `to_update` rows the caller previewed (optionally
	filtered down). Never adds/removes milestone rows - only sets
	is_completed/completed_on/remarks on rows that already exist, so the
	existing Forwarding Job guards (prevent_milestone_row_deletion,
	prevent_manual_milestone_rows) are unaffected. Returns per-row outcomes
	plus counts, for persisting into a Milestone Import Result table."""
	by_job = {}
	for update in updates or []:
		by_job.setdefault(update["job"], []).append(update)

	results = []

	for job_name, job_updates in by_job.items():
		if not frappe.has_permission("Forwarding Job", "write", job_name):
			for update in job_updates:
				results.append(
					{
						"job": job_name,
						"milestone_code": update["milestone_code"],
						"milestone_label": update["milestone_label"],
						"completed_on": update["completed_on"],
						"outcome": "Failed",
						"message": _("No write permission."),
					}
				)
			continue

		try:
			job = frappe.get_doc("Forwarding Job", job_name)
			job_results = []
			applied_in_job = 0
			for update in job_updates:
				milestone_rows = job.get(update["fieldname"]) or []
				target_row = next((r for r in milestone_rows if r.name == update["row_name"]), None)
				base = {
					"job": job_name,
					"milestone_code": update["milestone_code"],
					"milestone_label": update["milestone_label"],
					"completed_on": update["completed_on"],
				}
				if not target_row:
					job_results.append({**base, "outcome": "Skipped", "message": _("Milestone row not found.")})
					continue
				if target_row.is_completed:
					job_results.append({**base, "outcome": "Skipped", "message": _("Already completed.")})
					continue

				target_row.is_completed = 1
				target_row.completed_on = getdate(update["completed_on"])
				if not target_row.remarks:
					target_row.remarks = _("Imported from clearing tracker upload on {0}").format(nowdate())
				job_results.append({**base, "outcome": "Updated", "message": ""})
				applied_in_job += 1

			if applied_in_job:
				job.save()
			results.extend(job_results)
		except Exception as e:
			frappe.log_error(frappe.get_traceback(), f"Milestone import failed for Forwarding Job: {job_name}")
			for update in job_updates:
				results.append(
					{
						"job": job_name,
						"milestone_code": update["milestone_code"],
						"milestone_label": update["milestone_label"],
						"completed_on": update["completed_on"],
						"outcome": "Failed",
						"message": str(e),
					}
				)

	return {
		"results": results,
		"updated_count": sum(1 for r in results if r["outcome"] == "Updated"),
		"skipped_count": sum(1 for r in results if r["outcome"] == "Skipped"),
		"failed_count": sum(1 for r in results if r["outcome"] == "Failed"),
	}


@frappe.whitelist()
def download_import_template(service_module):
	"""Streams an .xlsx template for the given service module: a Job
	Reference column plus one column per active milestone, using the same
	header resolution as classify_rows so a filled-in template always
	re-imports cleanly."""
	check_freightmas_role()

	job_reference_header, column_map, header_by_code = _resolve_column_map(service_module)

	definitions = frappe.get_all(
		"Milestone Definition",
		filters={"service_module": service_module, "is_active": 1},
		fields=["milestone_code"],
		order_by="sequence asc",
	)

	header_row = [job_reference_header.title()] + [
		header_by_code.get(d.milestone_code, d.milestone_code) for d in definitions
	]

	build_xlsx_response([header_row], f"Milestone Import Template - {service_module}")
