# Copyright (c) 2026, Zvomaita Technologies (Pvt) Ltd
# For license information, please see license.txt

"""FreightMas Email Template body content and registry."""

from freightmas.notifications.email_templates.documentation_request import (
	DOCUMENTATION_REQUEST_TEMPLATE_HTML,
	DOCUMENTATION_REQUEST_TEMPLATE_NAME,
	DOCUMENTATION_REQUEST_TEMPLATE_SUBJECT,
)
from freightmas.notifications.email_templates.invoice_statement import (
	INVOICE_STATEMENT_TEMPLATE_HTML,
	INVOICE_STATEMENT_TEMPLATE_NAME,
	INVOICE_STATEMENT_TEMPLATE_SUBJECT,
)
from freightmas.notifications.email_templates.job_creation import (
	FORWARDING_JOB_CREATION_TEMPLATE_HTML,
	FORWARDING_JOB_CREATION_TEMPLATE_NAME,
	FORWARDING_JOB_CREATION_TEMPLATE_SUBJECT,
	JOB_CREATION_TEMPLATE_HTML,
	JOB_CREATION_TEMPLATE_NAME,
	JOB_CREATION_TEMPLATE_SUBJECT,
)
from freightmas.notifications.email_templates.status_update import (
	STATUS_UPDATE_TEMPLATE_HTML,
	STATUS_UPDATE_TEMPLATE_NAME,
	STATUS_UPDATE_TEMPLATE_SUBJECT,
)

TEMPLATE_REGISTRY = {
	JOB_CREATION_TEMPLATE_NAME: {
		"subject": JOB_CREATION_TEMPLATE_SUBJECT,
		"response_html": JOB_CREATION_TEMPLATE_HTML,
		"email_type": "SHIPMENT NOTIFICATION",
	},
	FORWARDING_JOB_CREATION_TEMPLATE_NAME: {
		"subject": FORWARDING_JOB_CREATION_TEMPLATE_SUBJECT,
		"response_html": FORWARDING_JOB_CREATION_TEMPLATE_HTML,
		"email_type": "SHIPMENT NOTIFICATION",
	},
	STATUS_UPDATE_TEMPLATE_NAME: {
		"subject": STATUS_UPDATE_TEMPLATE_SUBJECT,
		"response_html": STATUS_UPDATE_TEMPLATE_HTML,
		"email_type": "TRACKING UPDATE",
	},
	DOCUMENTATION_REQUEST_TEMPLATE_NAME: {
		"subject": DOCUMENTATION_REQUEST_TEMPLATE_SUBJECT,
		"response_html": DOCUMENTATION_REQUEST_TEMPLATE_HTML,
		"email_type": "DOCUMENTATION REQUEST",
	},
	INVOICE_STATEMENT_TEMPLATE_NAME: {
		"subject": INVOICE_STATEMENT_TEMPLATE_SUBJECT,
		"response_html": INVOICE_STATEMENT_TEMPLATE_HTML,
		"email_type": "ACCOUNTS — INVOICE",
	},
}

ALL_TEMPLATE_NAMES = list(TEMPLATE_REGISTRY.keys())
